---
# We just wrap `build` so this is really it
name: "jellyfin-ffmpeg"
version: "6.0-6"
packages:
  - buster-amd64
  - buster-armhf
  - buster-arm64
  - bullseye-amd64
  - bullseye-armhf
  - bullseye-arm64
  - bookworm-amd64
  - bookworm-armhf
  - bookworm-arm64
  - focal-amd64
  - focal-armhf
  - focal-arm64
  - jammy-amd64
  - jammy-armhf
  - jammy-arm64
  - kinetic-amd64
  - kinetic-armhf
  - kinetic-arm64
  - lunar-amd64
  - lunar-armhf
  - lunar-arm64
  - mantic-amd64
  - mantic-armhf
  - mantic-arm64
