---
# We just wrap `build` so this is really it
name: "jellyfin-ffmpeg"
version: "8.1.1-3"
packages:
  - bullseye-amd64
  - bullseye-arm64
  - bookworm-amd64
  - bookworm-arm64
  - trixie-amd64
  - trixie-arm64
  - trixie-riscv64
  - jammy-amd64
  - jammy-arm64
  - jammy-riscv64
  - noble-amd64
  - noble-arm64
  - noble-riscv64
  - resolute-amd64
  - resolute-arm64
  - resolute-riscv64