---
# We just wrap `build` so this is really it
name: "jellyfin-ffmpeg"
version: "5.0.1-2"
packages:
  - buster-amd64
  - buster-armhf
  - buster-arm64
  - bullseye-amd64
  - bullseye-armhf
  - bullseye-arm64
  - bionic-amd64
  - bionic-armhf
  - bionic-arm64
  - focal-amd64
  - focal-armhf
  - focal-arm64
  - impish-amd64
  - impish-armhf
  - impish-arm64
  - jammy-amd64
  - jammy-armhf
  - jammy-arm64
