#!/bin/sh

set -e

# build the examples

echo "ADTTMP directory: $AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

cp -r /usr/share/doc/ffmpeg/examples ./
cd examples

echo "building the examples..."
ret=0
make -k all 2>&1
ret=$?
echo "done!"

exit $ret
