#!/bin/sh

# build the examples

echo "ADTTMP directory: $ADTTMP"
cd "$ADTTMP"

cp -r /usr/share/doc/ffmpeg-doc/examples ./
cd examples

echo "building the examples..."
ret=0
make -k all 2>&1
ret=$?
echo "done!"

exit $ret
